---
- hosts: all
  gather_facts: yes
  become: false
  tasks:
  - name: Create a VM with existing vnet
    azure_rm_virtualmachine:
      resource_group: sk-centralus
      name: testvm2
      network_interfaces: sk-vnet-centralus
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.1'
        version: latest
  - name: Print all available facts
    ansible.builtin.debug:
      var: ansible_facts
