---
- name: azure_rm_resourcegroup_info EE run test
  hosts: all
#  gather_facts: false
  vars:
    sub_id: ""
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install packaging python package
      pip:
        name: packaging
        executable: pip3
  
    - name: run the info
      azure.azcollection.azure_rm_resourcegroup_info:
        name: AAPNightlyGroupsk
        subscription_id: "{{ sub_id }}"
      register: rg_info

    - debug: var=rg_info
