- name: Test Azure Connectivity
  hosts: localhost
  connection: local
  tasks:
    - name: Check connectivity to Azure API
      ansible.builtin.uri:
        url: https://management.azure.com/
        return_content: yes
