- name: Check Azure DNS Resolution & Connectivity
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Resolve Azure Management DNS using getent (Portable)
      ansible.builtin.command: getent hosts management.azure.com
      register: dns_lookup
      ignore_errors: yes

    - name: Display DNS Lookup Result
      debug:
        var: dns_lookup.stdout

    - name: Test IPv4 Connectivity to Azure API (Using Ansible Ping Module)
      ansible.builtin.ping:
      register: ansible_ping_v4
      ignore_errors: yes

    - name: Show IPv4 Ping Result
      debug:
        var: ansible_ping_v4

    - name: Test IPv6 Connectivity to Azure API (Using Ansible Ping Module)
      ansible.builtin.ping:
      register: ansible_ping_v6
      ignore_errors: yes

    - name: Show IPv6 Ping Result
      debug:
        var: ansible_ping_v6
