---
- name: azure_rm_resourcegroup_info EE run test
  hosts: all
  gather_facts: false
  tasks:
    - name: run the info
      azure.azcollection.azure_rm_resourcegroup_info:
        name: AAPNightlyGroupsk
      register: rg_info

    - debug: var=rg_info
